improve running from vscode tests sidebar
Balrog994/cucumber-test-runner pull request #11
Opened 2023-07-25 09:43 UTC by orine

1. when running test with before/after hooks, stdout stream throws an error event.
(catch it using: 
`process.stdout.on('error', function (err) {
  console.log(err);
});`
causing the runner to not calling `run.end();`

2. tests prints to stdout are now redirected to the debug console.

2023-07-25 10:08 UTC, Balrog994 commented
Thanks, for the pull request 👍 
Can you please fix the issues in this review?

Once fixed, I'll merge it in the main branch!

2023-07-25 11:21 UTC, orine commented
* this is exactly what the PR fixed.
* since i quickly patched your code just to make it work, i'm not sure this is the best fix. i would appriciate if you can review it just to make sure it aligns with your implmentation concept.

2023-07-25 12:15 UTC, Balrog994 commented
> * this is exactly what the PR fixed.
> * since i quickly patched your code just to make it work, i'm not sure this is the best fix. i would appriciate if you can review it just to make sure it aligns with your implementation concept.

We probably didn't understand each other 😄 

I already reviewed your Pull Request but I have no access to your fork so I cannot add commits to the pull request to fix the issues found out while reviewing. 
I highlighted the fixed as a review, you can see the thread above.
It would be great if you could fix those yourself so I can just merge the request and mark it as merged, otherwise I have to download the code, apply the changes manually and then mark the Pull Request as closed without being merged.

I would prefer the first, so that your contribution is correctly saved in the project history 😉 
I you can not or don't have time, just let me know!

Thanks again

2023-07-25 12:55 UTC, orine commented
i don't see any notes in this thread. can be please verify they are posted ?

2023-07-25 13:03 UTC, Balrog994 commented
> i don't see any notes in this thread. can be please verify they are posted ?

I assigned you to this pull request, can you see them now?

2023-07-25 13:08 UTC, orine commented
sorry, still can't see

2023-07-25 13:08 UTC, Balrog994 requested changes

2023-07-25 13:09 UTC, Balrog994 commented
ok, I forgot to complete the review, my bad 😭

2023-07-27 13:39 UTC, Balrog994 approved these changes
Thank you for your help, the pull request is approved!

2023-07-27 13:40 UTC, merged

2023-07-27 13:50 UTC, orine commented
can you please publish a new version to vscode market place, thanks